<?php
//
// CHUCKNORRIS - thanks to http://www.chucknorrisfacts.com/page2.html
//
$norrisquotes = array (
	"When Chuck Norris calls 1-900 numbers, he doesnt get charged. He holds up the phone and money falls out.",
	"Chuck Norris once ate a whole cake before his friends could tell him there was a stripper in it.",
	"Some people like to eat frogs' legs. Chuck Norris likes to eat lizard legs. Hence, snakes.",
	"There are no races, only countries of people Chuck Norris has beaten to different shades of black and blue.",
	"When Chuck Norris was denied an Egg McMuffin at McDonald's because it was 10:35, he roundhouse kicked the store so hard it became a Wendy's.",
	"Chuck Norris can't finish a 'color by numbers' because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red.",
	"A Chuck Norris-delivered Roundhouse Kick is the preferred method of execution in 16 states.",
	"When Chuck Norris falls in water, Chuck Norris doesn't get wet. Water gets Chuck Norris.",
	"Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (Chuck Norris Roundhouse Kick)",
	"Chuck Norris's house has no doors, only walls that he walks through.",
	"How much wood would a woodchuck chuck if a woodchuck could Chuck Norris? ...All of it.",
	"Chuck Norris doesn't actually write books, the words assemble themselves out of fear.",
	"In honor of Chuck Norris, all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be Chucksized.",
	"Chuck Norris CAN believe it's not butter.",
	"If tapped, a Chuck Norris roundhouse kick could power the country of Australia for 44 minutes.",
	"Chuck Norris can divide by zero.",
	"The grass is always greener on the other side, unless Chuck Norris has been there. In that case the grass is most likely soaked in blood and tears.",
	"A picture is worth a thousand words. A Chuck Norris is worth 1 billion words.",
	"Newton's Third Law is wrong: Although it states that for each action, there is an equal and opposite reaction, there is no force equal in reaction to a Chuck Norris roundhouse kick.",
	"Chuck Norris invented his own type of karate. It's called Chuck-Will-Kill.",
	"When an episode of Walker Texas Ranger was aired in France, the French surrendered to Chuck Norris just to be on the safe side.",
	"While urinating, Chuck Norris is easily capable of welding titanium.",
	"Chuck Norris once sued the Houghton-Mifflin textbook company when it became apparent that their account of the war of 1812 was plagiarized from his autobiography.",
	"When Chuck Norris talks, everybody listens. And dies.",
	"When Steven Seagal kills a ninja, he only takes its hide. When Chuck Norris kills a ninja, he uses every part.",
	"Contrary to popular belief, there is indeed enough Chuck Norris to go around.",
	"Chuck Norris doesnt shave; he kicks himself in the face. The only thing that can cut Chuck Norris is Chuck Norris.",
	"For some, the left testicle is larger than the right one. For Chuck Norris, each testicle is larger than the other one.",
	"Chuck Norris always knows the EXACT location of Carmen SanDiego.",
	"When taking the SAT, write 'Chuck Norris' for every answer. You will score over 8000.",
	"Chuck Norris invented black. In fact, he invented the entire spectrum of visible light. Except pink. Tom Cruise invented pink.",
	"When you're Chuck Norris, anything + anything is equal to 1. One roundhouse kick to the face.",
	"Chuck Norris has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoloy card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO.",
	"On his birthday, Chuck Norris randomly selects one lucky child to be thrown into the sun.",
	"Nobody doesn't like Sara Lee. Except Chuck Norris.",
	"Chuck Norris doesn't throw up if he drinks too much. Chuck Norris throws down!",
	"In the beginning there was nothing...then Chuck Norris Roundhouse kicked that nothing in the face and said 'Get a job'. That is the story of the universe.",
	"Chuck Norris has 12 moons. One of those moons is the Earth.",
	"Chuck Norris grinds his coffee with his teeth and boils the water with his own rage.",
	"Archeologists unearthed an old english dictionary dating back to the year 1135. It defined 'victim' as 'one who has encountered Chuck Norris'.",
	"Chuck Norris ordered a Big Mac at Burger King, and got one.",
	"Chuck Norris and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building.",
	"If you Google search 'Chuck Norris getting his ass kicked' you will generate zero results. It just doesn't happen.",
	"Chuck Norris can drink an entire gallon of milk in thirty-seven seconds.",
	"Little known medical fact: Chuck Norris invented the Caesarean section when he roundhouse-kicked his way out of his monther's womb.",
	"Chuck Norris doesn't bowl strikes, he just knocks down one pin and the other nine faint.",
	"The show Survivor had the original premise of putting people on an island with Chuck Norris. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage.",
	"It takes Chuck Norris 20 minutes to watch 60 Minutes.",
	"You know how they say if you die in your dream then you will die in real life? In actuality, if you dream of death then Chuck Norris will find you and kill you.",
	"Chuck Norris has a deep and abiding respect for human life... unless it gets in his way.",
	"The Bermuda Triangle used to be the Bermuda Square, until Chuck Norris Roundhouse kicked one of the corners off.",
	"There are no weapons of mass destruction in Iraq, Chuck Norris lives in Oklahoma.",
	"Chuck Norris doesn't believe in Germany.",
	"When Chuck Norris is in a crowded area, he doesn't walk around people. He walks through them.",
	"Chuck Norris once ate an entire bottle of sleeping pills. They made him blink.",
	"James Cameron wanted Chuck Norris to play the Terminator. However, upon reflection, he realized that would have turned his movie into a documentary, so he went with Arnold Schwarzenegger.",
	"Chuck Norris can touch MC Hammer.",
	"Thousands of years ago Chuck Norris came across a bear. It was so terrified that it fled north into the arctic. It was also so terrified that all of its decendents now have white hair.",
	"Chuck Norris played Russian Roulette with a fully loaded gun and won.",
	"It takes 14 puppeteers to make Chuck Norris smile, but only 2 to make him destroy an orphanage.",
	"Chuck Norris is the reason waldo is hiding."
);
$count = count($norrisquotes);
$randnorris = rand(0,$count-1);
$irc->message(SMARTIRC_TYPE_CHANNEL, $recip, $norrisquotes[$randnorris]);
?>